import turtle as t


def house(m, n, x):
    # TODO: Ilya
    t.up()
    t.goto(m, n)
    t.fd(2 * x)
    t.down()
    t.right(120)
    t.fd(2 * x)
    t.left(120)
    t.fd(2 * x)
    t.left(120)
    t.fd(2 * x)
    t.left(180)
    t.fd(2 * x)
    t.right(30)
    t.fd(2 * x)
    t.right(90)
    t.fd(2 * x)
    t.right(90)
    t.fd(2 * x)
    t.up()
    t.right(180)
    t.fd(x // 3)
    t.left(90)
    t.fd(x // 3)
    t.down()
    y = x // 3 * 2
    t.fd(2 * y)
    t.right(90)
    t.fd(2 * y)
    t.right(90)
    t.fd(2 * y)
    t.right(90)
    t.fd(2 * y)
    t.right(90)
    t.fd(y)
    t.right(90)
    t.fd(y)
    t.right(90)
    t.fd(y)
    t.right(180)
    t.fd(2 * y)
    t.right(180)
    t.fd(y)
    t.right(90)
    t.fd(y)
    t.right(180)
    t.fd(2 * y)
    t.left(90)


def el(m, n, x):
    t.up()
    t.goto(m, n)
    t.fd(x / 2)
    t.down()
    for i in range(3):
        t.right(120)
        t.fd(x)
        t.left(120)
        t.fd(x)
        t.left(120)
        t.fd(x)
        t.left(120)
        t.fd(x)
        t.left(120)
        t.fd(x/2)
        x += x / 2
    t.fd(x/16)
    t.right(90)
    t.fd(x / 4)
    t.right(90)
    t.fd(x/8)
    t.right(90)
    t.fd(x / 4)
    t.right(90)


def dog(m, n, x):
    # TODO: Platon
    t.up()
    t.goto(m, n)
    t.fd(4 * x)
    t.down()
    t.right(90)
    t.fd(2 * x)
    t.right(90)
    t.fd(2 * x)
    t.left(90)
    t.fd(2 * x)
    t.left(90)
    t.fd(x)
    t.left(90)
    t.fd(x)
    t.right(90)
    t.fd(x)
    t.right(90)
    t.fd(x)
    t.left(90)
    t.fd(x)
    t.left(90)
    t.fd(x * 2)
    t.right(90)
    t.fd(x)
    t.left(90)
    t.fd(x)
    t.left(90)
    t.fd(x)
    t.right(90)
    t.fd(x)
    t.left(90)
    t.fd(x)


def machine(m, n, x):
    # TODO: Platon
    t.up()
    t.goto(m, n)
    t.fd(4 * x)
    t.down()
    t.right(90)
    t.fd(x)
    t.right(90)
    t.fd(x)
    t.left(90)
    t.fd(x)
    t.right(90)
    t.fd(x)
    t.right(90)
    t.fd(x)
    t.left(90)
    t.fd(x)
    t.left(90)
    t.fd(x)
    t.right(90)
    t.fd(x)
    t.right(90)
    t.fd(x)
    t.left(90)
    t.fd(x)
    t.right(90)
    t.fd(x)
    t.right(90)
    t.fd(x)
    t.left(90)
    t.fd(x)
    t.right(90)
    t.fd(3 * x)
    t.right(90)
    t.fd(x)
    t.left(90)
    t.fd(x)


def snk(m, n, y, x):
    # TODO: Nadia
    t.up()
    t.goto(m, n)
    t.down()
    t.fd(2 * y)
    t.left(90)
    t.fd(y)
    t.left(90)
    t.fd(3 * y)
    t.left(90)
    t.fd(4 * y)
    t.right(90)
    t.fd(4 * y)
    t.left(90)
    t.fd(3 * y)
    t.left(90)
    t.fd(7 * y)
    t.left(90)
    t.fd(7 * x)
    t.right(220)
    t.fd(3 * x)
    t.left(40)
    t.fd(3 * x)
    t.right(90)
    t.fd(10 * x)
    t.right(90)
    t.fd(2 * x)
    t.right(90)
    t.fd(8 * x)
    t.left(90)
    t.fd(x * 8)
    t.fd(x//5)


def snk_1(m,n,y,x):
    #TODO: Nadia
    t.up()
    t.goto(m,n)
    t.down()
    t.fd(2 * y)
    t.left(90)
    t.fd(y)
    t.left(90)
    t.fd(3 * y)
    t.left(90)
    t.fd(4 * y)
    t.right(90)
    t.fd(6 * y)
    t.right(90)
    t.fd(5 * x)
    t.right(90)
    t.fd(3 * x)
    t.right(90)
    t.fd(3 * x)
    t.left(120)
    t.fd(2 * x)
    t.left(60)
    t.fd(2 * y)
    t.left(90)
    t.fd(7 * x)
    t.left(90)
    t.fd(9 * x)
    t.left(90)
    t.fd(16 * x)
    t.fd(x//5)
    t.left(90)
    t.fd(8 * x   
    
    

t.speed(100)
house(-800, 350, 50)
el(-725, 100, 50)
machine(-550, 250, 30)
dog(-650, 100, 30)

# machine(100, 100, 100)
# snk(100, 100, 50, 25)
# snk_1(100, 100, 50, 25)  
t.mainloop()
