import turtle as t
def house(m, n, x):
    # TODO: Ilya
    t.up()
    t.goto(m, n)
    t.fd(2 * x)
    t.down()
    t.right(120)
    t.fd(2 * x)
    t.left(120)
    t.fd(2 * x)
    t.left(120)
    t.fd(2 * x)
    t.left(180)
    t.fd(2 * x)
    t.right(30)
    t.fd(2 * x)
    t.right(90)
    t.fd(2 * x)
    t.right(90)
    t.fd(2 * x)
    t.up()
    t.right(180)
    t.fd(x // 3)
    t.left(90)
    t.fd(x // 3)
    t.down()
    y = x // 3 * 2
    t.fd(2 * y)
    t.right(90)
    t.fd(2 * y)
    t.right(90)
    t.fd(2 * y)
    t.right(90)
    t.fd(2 * y)
    t.right(90)
    t.fd(y)
    t.right(90)
    t.fd(y)
    t.right(90)
    t.fd(y)
    t.right(180)
    t.fd(2 * y)
    t.right(180)
    t.fd(y)
    t.right(90)
    t.fd(y)
    t.right(180)
    t.fd(2 * y)

def sneg(m, n, r):
    # TODO: Ilya
    t.up()
    t.goto(m, n)
    t.fd(r)
    t.down()
    t.fd(2 * r)
    t.right(90)
    t.fd(3 * r)
    t.right(90)
    t.fd(2 * r)
    t.right(90)
    t.fd(r)
    t.up()
    t.goto(m + r, n + 4 * r)
    t.down()
    t.circle(r)
    t.up()
    t.goto(m + r, n + 7 * r)
    t.down()
    t.circle(r * 2)

def dog(m, n, x):
    # TODO: Platon
    t.up()
    t.goto(m, n)
    t.fd(4 * x)
    t.down()
    t.right(90)
    t.fd(2 * x)
    t.right(90)
    t.fd(2 * x)
    t.left(90)
    t.fd(2 * x)
    t.left(90)
    t.fd(x)
    t.left(90)
    t.fd(x)
    t.right(90)
    t.fd(x)
    t.right(90)
    t.fd(x)
    t.left(90)
    t.fd(x)
    t.left(90)
    t.fd(x * 2)
    t.right(90)
    t.fd(x)
    t.left(90)
    t.fd(x)
    t.left(90)
    t.fd(x)
    t.right(90)
    t.fd(x)
    t.left(90)
    t.fd(x)

def machine(m, n, x):
    # TODO: Platon
    t.up()
    t.goto(m, n)
    t.fd(4 * x)
    t.down()
    t.right(90)
    t.fd(x)
    t.right(90)
    t.fd(x)
    t.left(90)
    t.fd(x)
    t.right(90)
    t.fd(x)
    t.right(90)
    t.fd(x)
    t.left(90)
    t.fd(x)
    t.left(90)
    t.fd(x)
    t.right(90)
    t.fd(x)
    t.right(90)
    t.fd(x)
    t.left(90)
    t.fd(x)
    t.right(90)
    t.fd(x)
    t.right(90)
    t.fd(x)
    t.left(90)
    t.fd(x)
    t.right(90)
    t.fd(3 * x)
    t.right(90)
    t.fd(x)
    t.left(90)
    t.fd(x)
machine(100, 100, 100)

def sqare(x,m,n):
 #TODO(Nadia)
    t.up()  #левый глаз
    t.goto(m,n)
    t.down()
    t.forward(x)
    t.left(90)
    t.forward(x)
    t.left(90)
    t.forward(x)
    t.left(90)
    t.forward(x)
    t.left(90)
sqare(100, -700, 200)

def sqare_1(g,m,n):
# TODO(Nadia)
    t.up()     #левый зрачек
    t.goto(m, n)
    t.down()
    t.forward(g)
    t.left(90)
    t.forward(g)
    t.left(90)
    t.forward(g)
    t.left(90)
    t.forward(g)
    t.left(90)
sqare_1(50, -700, 200)

def sqare_2(x,m,n):
# TODO(Nadia)
    t.up()     #правый глаз
    t.goto(m,n)
    t.down()
    t.forward(x)
    t.left(90)
    t.forward(x)
    t.left(90)
    t.forward(x)
    t.left(90)
    t.forward(x)
    t.left(90)
sqare_2(100, -500, 200)

def sqare_3(g,m,n):
# TODO(Nadia)
    t.up()     #правый зрачек
    t.goto(m,n)
    t.down()
    t.forward(g)
    t.left(90)
    t.forward(g)
    t.left(90)
    t.forward(g)
    t.left(90)
    t.forward(g)
    t.left(90)
sqare_3(50,-500,200)

def sqare_4(m,n,z,c):
    #TODO(Nadia)
    t.up()  # рот
    t.goto(m,n)
    t.down()
    t.forward(z)
    t.left(90)
    t.forward(c)
    t.left(90)
    t.forward(z)
    t.left(90)
    t.forward(c)
    t.left(90)
sqare_4(-650,100,100,70,)


def sqare_5(u,e,w):
 #TODO(Nadia)
    t.up()  #левый глаз
    t.goto(e,w)
    t.down()
    t.forward(u)
    t.left(90)
    t.forward(u)
    t.left(90)
    t.forward(u)
    t.left(90)
    t.forward(u)
    t.left(90)
sqare_5(100,100,-700)

def sqare_6(u,d,f):
    # TODO(Nadia)
    t.up()     #левый зрачек
    t.goto(d, f)
    t.down()
    t.forward(u)
    t.left(90)
    t.forward(u)
    t.left(90)
    t.forward(u)
    t.left(90)
    t.forward(u)
    t.left(90)
sqare_6(100,-200,50)

def sqare_7(u, a, s):
    # TODO(Nadia)
    t.up()     #правый глаз
    t.goto(a,s)
    t.down()
    t.forward(u)
    t.left(90)
    t.forward(u)
    t.left(90)
    t.forward(u)
    t.left(90)
    t.forward(u)
    t.left(90)
sqare_7(100,-500,200)

def sqare_7(u, h,j):
    # TODO(Nadia)
    t.up()     #правый зрачек
    t.goto(h,j)
    t.down()
    t.forward(u)
    t.left(90)
    t.forward(u)
    t.left(90)
    t.forward(u)
    t.left(90)
    t.forward(u)
    t.left(90)
sqare_7(100,-500,-200)

def sqare_8(k,l,z,c):
    #TODO(Nadia)
    t.up()  # рот
    t.goto(k,l)
    t.down()
    t.forward(z)
    t.left(90)
    t.forward(c)
    t.left(90)
    t.forward(z)
    t.left(90)
    t.forward(c)
    t.left(90)
sqare_8(-550,-300,100,70,)
